CREATE DATABASE telecom_project;
USE telecom_project;
SELECT * FROM telecom LIMIT 5;
SELECT COUNT(*) AS total_customers FROM telecom;
SELECT COUNT(*) AS total_customers FROM telecom WHERE Churn='Yes';
SELECT ROUND (SUM(CASE WHEN Churn='Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS churn_rate FROM telecom;
SELECT Contract , COUNT(*) AS churn_customers FROM telecom WHERE Churn='Yes' GROUP BY Contract ORDER BY churn_customers DESC;
SELECT PaymentMethod , COUNT(*) AS total_customers FROM telecom GROUP BY PaymentMethod ORDER BY total_customers DESC;
SELECT InternetService , COUNT(*) AS total_customers FROM telecom GROUP BY InternetService;
SELECT gender , COUNT(*) AS churn_customers FROM telecom WHERE Churn='Yes' GROUP BY gender;
SELECT SeniorCitizen , COUNT(*) churn_customer FROM telecom WHERE Churn='Yes' GROUP BY SeniorCitizen;
SELECT AVG(MonthlyCharges) AS avg_monthlycharges FROM telecom;
SELECT Churn , AVG (MonthlyCharges) AS avg_monthlycharges FROM telecom GROUP BY Churn;
SELECT Contract, AVG(MonthlyCharges) AS avng_monthlycharges FROM telecom GROUP BY Contract;
SELECT Churn , AVG (tenure) AS avg_tenure FROM telecom GROUP BY Churn;
SELECT PaymentMethod , COUNT(*) AS churn_customers FROM telecom WHERE Churn='Yes' GROUP BY PaymentMethod ORDER BY churn_customers DESC;
SELECT InternetService , COUNT(*) AS churn_customers FROM telecom WHERE Churn='Yes' GROUP BY InternetService ORDER BY churn_customers DESC;
SELECT PaperlessBilling , COUNT(*) AS churn_customers FROM telecom WHERE Churn='Yes' GROUP BY PaperlessBilling;
SELECT TechSupport,COUNT(*) AS churn_customers FROM telecom WHERE Churn = 'Yes' GROUP BY TechSupport;
SELECT OnlineSecurity, COUNT(*) AS churn_customers FROM telecom WHERE Churn = 'Yes' GROUP BY OnlineSecurity;
SELECT StreamingTV, COUNT(*) AS churn_customers FROM telecom WHERE Churn = 'Yes' GROUP BY StreamingTV;
SELECT customerID, MonthlyCharges, TotalCharges FROM telecom ORDER BY TotalCharges DESC LIMIT 10;